services:
  tmodloader:
    image: 'jacobsmile/tmodloader1.4:latest'
    container_name: 'tmodloader'
    ports:
      - "7777:7777"
    expose:
      - "7777"
    environment:
      # Download the Calamity mod and CalamityMusic mod.
      - "TMOD_AUTODOWNLOAD=2909886416,2619954303,3234262967,2563309347,2908170107,2824688072,2824688266,2987060992,2669644269,2847472897,2836679312"
      # Enable the Calamity mod and CalamityMusic mod.
      - "TMOD_ENABLEDMODS=2909886416,2619954303,3234262967,2563309347,2908170107,2824688072,2824688266,2987060992,2669644269,2847472897,2836679312"
      # Shutdown Message and Autosave Interval (In Minutes)
      - "TMOD_SHUTDOWN_MESSAGE=Goodbye!"
      - "TMOD_AUTOSAVE_INTERVAL=15"
      # Server Settings
      - "TMOD_MOTD=Welcome to my tModLoader Server!"
      - "TMOD_PASS=secret"
      - "TMOD_MAXPLAYERS=16"
      # The following world settings are only used when generating a new world.
      - "TMOD_WORLDNAME=vivable_Utopie"
      - "TMOD_WORLDSIZE=3"
      - "TMOD_WORLDSEED=Bonjour michel"
      - "TMOD_DIFFICULTY=3"
      # (Deprecated) If TMOD_USECONFIGFILE is set to "Yes", it is expected to have a serverconfig.txt mapped. The Server Settings above will be ignored.
      - "TMOD_USECONFIGFILE=No"
      - "UPDATE_NOTICE=false"
    volumes:
      - "./data:/data"
